### ISSUE TITLE
Improve orientation non supported feedback

### ISSUE THREAD

**Issue by tekreme73** [abdonrd/device-orientation#1]
Hi,

When using this component, we may need to know if the orientation is supported or not by the device.

Maybe add another property to know if the orientation is available or not.

**Comment by abdonrd** [comment]
Thanks! Would you like to send a PR?

**Comment by FluorescentHallucinogen** [comment]
@abdonrd I'll send a pull request as soon as I have some free time. :wink:

**Comment by FluorescentHallucinogen** [comment]
See #5. :wink:

**Comment by FluorescentHallucinogen** [comment]
@abdonrd Please reopen this issue until #7 will be implemented. The `api-supported` property indicates whether Device Orientation API is supported or not by the **browser**. The `sensors-available` property indicates whether relevant sensors are available or not in the **device**.

**Comment by FluorescentHallucinogen** [comment]
Fixed in #9. Can be closed.
