### ISSUE TITLE
Upgrade to Polymer 2.x support

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [abdonrd/device-orientation#2]
Update this web component to Polymer 2.x support.

**Comment by FluorescentHallucinogen** [comment]
@abdonrd I'll send a pull request as soon as I have some free time. :wink:

**Comment by abdonrd** [comment]
The element should already support Polymer 2.x, because it doesn't use DOM template or Shadow DOM styles:

https://www.polymer-project.org/2.0/docs/upgrade#upgrade-an-element

**Comment by FluorescentHallucinogen** [comment]
Then I'll update `bower.json` as soon as I have some free time.

What minimum possible version of Polymer can be used with this web component, `v1.6.0` or `v1.0.0`?

**Comment by abdonrd** [comment]
Probably it should work in `v1.0.0` too.
