### ISSUE TITLE
Web components for Motion Sensors APIs based on Generic Sensor API

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [abdonrd/device-orientation#4]
@abdonrd What about web components for Motion Sensors APIs based on Generic Sensor API (https://www.chromestatus.com/feature/5698781827825664)?

See it in action:
https://sensor-compass.appspot.com (https://github.com/01org/websensor-compass)
https://genericsensors.appspot.com (https://github.com/01org/websensor-sensor-info)

**Comment by abdonrd** [comment]
Sounds really great!

But right now I haven't much time to dedicate it.

**Comment by FluorescentHallucinogen** [comment]
I believe that Motion Sensors APIs based on Generic Sensor API should be implemented in a separate web component.

But I can add support of DeviceMotionEvent (that is not based on Generic Sensor API) to this web component.

DeviceMotionEvent has the following properties:

`event.acceleration.x`
`event.acceleration.y`
`event.acceleration.z`
`event.accelerationIncludingGravity.x`
`event.accelerationIncludingGravity.y`
`event.accelerationIncludingGravity.z`
`event.rotationRate.alpha`
`event.rotationRate.beta`
`event.rotationRate.gamma`

**Comment by FluorescentHallucinogen** [comment]
I'll send a pull request with `device-motion.html` as soon as I have some free time. :wink:

**Comment by FluorescentHallucinogen** [comment]
See #10.

**Comment by abdonrd** [comment]
Closed by #10.
