### ISSUE TITLE
Add "alpha", "beta", "gamma" and "absolute" properties

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [abdonrd/device-orientation#6]
@abdonrd Is it a good idea to add individual properties (`alpha`, `beta`, `gamma` and `absolute`) to this web component?

**Comment by abdonrd** [comment]
I'm not sure what is the best option, but both (only orientation or the four properties) should work.

**Comment by abdonrd** [comment]
Finally, I'd rather offer the original API.
